auto: true

markdown: rdiscount

highlighter: 'pygments'
#paginate: 8
permalink: /:title

name: “Levirena”
title: Levirena说不想陪你喝伪电气白兰
description: For documenting. 
url: http://levirena.github.io
feed: /atom.xml
author_info: <a href="http://mukosame.github.io/">Mukosame</a>
